### ISSUE TITLE
Migrate l1_distances to use trio.encryptBatch

### ISSUE THREAD

**Issue by mackncheesiest** [mackncheesiest/ECE509_AdversarialCryptography#6]
Encrypting only one plaintext per tensorflow session run just isn't a feasible way of computing all the nearest neighbors as I found out while finishing map_cipherspace.

So, we need to do them in batches (i.e. pass a batch of plaintexts and then compute the NN distances for the entries in that batch)

**Comment by codygunton** [comment]
Done in batch_extreme_l1_distances in neighbors.py. Could keep the other distances too, but I think looking at the min distances is probably enough for some insight.
